spring:
  mvc.view:
    prefix: /WEB-INF/
    suffix: .jsp

moviefun:
  datasources:
    movies:
      url: jdbc:mysql://localhost:3306/movies?useSSL=false
      username: root
      password:
    albums:
      url: jdbc:mysql://localhost:3306/albums?useSSL=false
      username: root
      password:
VCAP_SERVICES: '{"p-mysql": [{"credentials": {"jdbcUrl": "jdbc:mysql://127.0.0.1:3306/albums?user=root"}, "name": "albums-mysql"}, {"credentials": {"jdbcUrl": "jdbc:mysql://127.0.0.1:3306/movies?user=root"}, "name": "movies-mysql"}]}'
